# Generated by Django 5.0.2 on 2024-12-08 13:57

import django.template.defaulttags
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('exam_date', models.DateField(default=django.template.defaulttags.now)),
                ('stud_desc', models.TextField()),
                ('password', models.CharField(default='temporary_password', max_length=128)),
            ],
        ),
    ]
