# Generated by Django 5.0.2 on 2024-12-08 14:19

import django.template.defaulttags
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='exam_date',
            field=models.DateTimeField(default=django.template.defaulttags.now),
        ),
    ]
