# Generated by Django 5.0.2 on 2024-12-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0002_alter_members_exam_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
