# Generated by Django 5.0.2 on 2024-12-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0003_rename_members_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='exam_date',
            field=models.DateTimeField(),
        ),
    ]
