# Generated by Django 5.1.4 on 2024-12-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0006_exam_remove_member_stud_desc_studentregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
