# Generated by Django 5.1.4 on 2024-12-12 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0008_remove_studentregistration_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentregistration',
            unique_together={('user', 'exam')},
        ),
    ]
